## MysteryBox CI/CD

image: python:3.10

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - pip install opencv-python
    - pip install -r requirements.txt
    - pip install -r older-requirements.txt
  

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - python -m unittest discover -s tests




